###Get
GET http://localhost:3000/api/users/get

###Get specific product
GET http://localhost:3000/api/users/{nanoid}

###Post
POST http://localhost:3000/api/users
Content-Type: application/json

{
    "username": "Zaai90",
    "password": "asd123",
    "email": "erik@suvnet.se",
    "firstname": "Erik",
    "lastname": "Grune",
    "role": "admin"
}

### GET / Not found error
GET http://localhost:3000/api/

###Post Test wrong data
POST http://localhost:3000/api/users/
Content-Type: application/json

{
    "namn": "Wrong pear",
    "pris": 10
}

###PUT
PUT http://localhost:3000/api/users/{}
Content-Type: application/json

{
    "name": "Pear",
    "price": 10
}

###Delete
Delete http://localhost:3000/api/users/delete/xOI_TxqbXSFVWLlopAfUk