###Get
GET http://localhost:3000/api/products/

###Post
POST http://localhost:3000/api/products/
Content-Type: application/json

{
    "name": "Apple",
    "price": 10
}

###Post Test wrong data
POST http://localhost:3000/api/products/
Content-Type: application/json

{
    "id": 10,
    "name": "Wrong pear",
    "price": 10
}

###Get specific product
GET http://localhost:3000/api/products/1
